// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2iLJkT5RuJ0evsINnOJaxu0Dze-3ha1I',
    appId: '1:970999773474:web:1050a94d773474433c0d7b',
    messagingSenderId: '970999773474',
    projectId: 'bookbloom-3afae',
    authDomain: 'bookbloom-3afae.firebaseapp.com',
    storageBucket: 'bookbloom-3afae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAR3-s-jblF4NG-GOycLnIsyI3RZi8Z4k',
    appId: '1:970999773474:android:065d6767e2d222153c0d7b',
    messagingSenderId: '970999773474',
    projectId: 'bookbloom-3afae',
    storageBucket: 'bookbloom-3afae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhf6i-QYT_65BIzJgAp6CwL15J2DNy0OE',
    appId: '1:970999773474:ios:40b7cab0873d525e3c0d7b',
    messagingSenderId: '970999773474',
    projectId: 'bookbloom-3afae',
    storageBucket: 'bookbloom-3afae.firebasestorage.app',
    iosBundleId: 'com.example.bookbloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhf6i-QYT_65BIzJgAp6CwL15J2DNy0OE',
    appId: '1:970999773474:ios:40b7cab0873d525e3c0d7b',
    messagingSenderId: '970999773474',
    projectId: 'bookbloom-3afae',
    storageBucket: 'bookbloom-3afae.firebasestorage.app',
    iosBundleId: 'com.example.bookbloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2iLJkT5RuJ0evsINnOJaxu0Dze-3ha1I',
    appId: '1:970999773474:web:a3ff6f5ad0bcd3203c0d7b',
    messagingSenderId: '970999773474',
    projectId: 'bookbloom-3afae',
    authDomain: 'bookbloom-3afae.firebaseapp.com',
    storageBucket: 'bookbloom-3afae.firebasestorage.app',
  );
}
